export type LegacyRetentionDecision = "keep" | "merge";

export type LegacyMappedAgent = "executive" | "sales" | "research" | "operations" | "customer" | "recruiting";

export type LegacyArchiveEntry = {
  id: string;
  displayName: string;
  sourceFiles: string[];
  expertGroup:
    | "revenue_intelligence"
    | "opportunity_analysis"
    | "outreach_messaging"
    | "market_research"
    | "executive_finance"
    | "legal_policy_ip"
    | "people_talent";
  mappedAgents: LegacyMappedAgent[];
  summary: string;
  expectedInputs: string[];
  expectedOutputs: string[];
  artifactBehavior: "suggest_save" | "artifact_friendly" | "save_on_request";
  approvalBehavior: "none" | "gmail_send" | "hubspot_crm_write" | "downstream_external_only";
  retention: LegacyRetentionDecision;
  mergedIntoExpertTypes?: string[];
};

export const legacyArchiveInventory: LegacyArchiveEntry[] = [
  {
    id: "boardpack-intelligence",
    displayName: "BoardPack Intelligence",
    sourceFiles: ["boardpack-intelligence-v7.html"],
    expertGroup: "executive_finance",
    mappedAgents: ["executive"],
    summary: "Board pack generation and analysis with financial narratives, board priorities, and anticipated questions.",
    expectedInputs: ["Board materials", "financial statements", "operating updates"],
    expectedOutputs: ["Executive brief", "board review", "financial narrative"],
    artifactBehavior: "artifact_friendly",
    approvalBehavior: "none",
    retention: "keep",
  },
  {
    id: "competitor-watch",
    displayName: "Competitor Watch",
    sourceFiles: ["competitor-watch-v3.1.html", "competitor-watch-indepth-v3.0.html"],
    expertGroup: "market_research",
    mappedAgents: ["research", "sales"],
    summary: "Competitor monitoring and deep-dive analysis for positioning, pricing, product gaps, and attack angles.",
    expectedInputs: ["Your company context", "competitor name or market set", "market focus"],
    expectedOutputs: ["Competitor battlecard", "watch brief", "attack-angle summary"],
    artifactBehavior: "suggest_save",
    approvalBehavior: "none",
    retention: "merge",
    mergedIntoExpertTypes: ["competitor_battlecard"],
  },
  {
    id: "connection-intelligence",
    displayName: "Connection Intelligence Engine",
    sourceFiles: ["connection-intelligence-v3_1.html"],
    expertGroup: "revenue_intelligence",
    mappedAgents: ["sales", "executive"],
    summary: "Relationship and overlap analysis for networking, conference intros, and warm-meeting angles.",
    expectedInputs: ["Two companies", "people or event context", "meeting goal"],
    expectedOutputs: ["Connection brief", "intro angle", "why-meet rationale"],
    artifactBehavior: "save_on_request",
    approvalBehavior: "none",
    retention: "merge",
    mergedIntoExpertTypes: ["contact_brief", "pre_call_brief"],
  },
  {
    id: "contact-engine",
    displayName: "Contact Intelligence Engine",
    sourceFiles: ["contact-engine-v8.html"],
    expertGroup: "revenue_intelligence",
    mappedAgents: ["sales"],
    summary: "Prospect and contact intelligence with persona, pain-point, and buying-signal analysis.",
    expectedInputs: ["Person or company details", "CRM context", "notes or profile links"],
    expectedOutputs: ["Buyer profile", "signals", "pain points", "next actions"],
    artifactBehavior: "suggest_save",
    approvalBehavior: "none",
    retention: "keep",
  },
  {
    id: "contractshield",
    displayName: "ContractShield",
    sourceFiles: ["contractshield-v2.4.html"],
    expertGroup: "legal_policy_ip",
    mappedAgents: ["operations", "research"],
    summary: "Contract risk analysis, clause comparison, and redline support.",
    expectedInputs: ["One or two contracts", "negotiation context"],
    expectedOutputs: ["Risk report", "comparison table", "redline guidance"],
    artifactBehavior: "artifact_friendly",
    approvalBehavior: "downstream_external_only",
    retention: "keep",
  },
  {
    id: "creative-studio",
    displayName: "AI Writing Studio",
    sourceFiles: ["creative-studio-v6.9.html", "iterative-rewrite-v2.1.html", "Article_Writer_v4.4.html"],
    expertGroup: "outreach_messaging",
    mappedAgents: ["sales", "operations", "customer"],
    summary: "Drafting, rewriting, and scoring content across outreach, articles, and business writing.",
    expectedInputs: ["Brief", "draft text", "audience", "tone", "channel"],
    expectedOutputs: ["Draft content", "rewrite suggestions", "structured rationale"],
    artifactBehavior: "save_on_request",
    approvalBehavior: "gmail_send",
    retention: "merge",
    mergedIntoExpertTypes: ["outreach_draft"],
  },
  {
    id: "deal-command-centre",
    displayName: "Deal Command Centre",
    sourceFiles: ["deal-command-centre-v9.html"],
    expertGroup: "opportunity_analysis",
    mappedAgents: ["sales", "executive"],
    summary: "Deal room-style opportunity analysis with readiness scoring and strategic next moves.",
    expectedInputs: ["Deal or company context", "goals", "documents", "constraints"],
    expectedOutputs: ["Opportunity scorecard", "deal analysis", "recommended plays"],
    artifactBehavior: "suggest_save",
    approvalBehavior: "hubspot_crm_write",
    retention: "keep",
  },
  {
    id: "eu-ai-act-assessor",
    displayName: "EU AI Act Assessor",
    sourceFiles: ["eu-ai-act-assessor-v2.4.html"],
    expertGroup: "legal_policy_ip",
    mappedAgents: ["research", "operations"],
    summary: "EU AI Act risk classification and compliance triage.",
    expectedInputs: ["AI system description", "use case context", "data and process details"],
    expectedOutputs: ["Risk class", "compliance assessment", "research gaps"],
    artifactBehavior: "suggest_save",
    approvalBehavior: "none",
    retention: "keep",
  },
  {
    id: "exit-interview-analyzer",
    displayName: "Exit Interview Analyzer",
    sourceFiles: ["exit-interview-analyzer-v8b.html"],
    expertGroup: "people_talent",
    mappedAgents: ["recruiting", "executive"],
    summary: "Theme and risk analysis across exit interviews and people signals.",
    expectedInputs: ["Exit transcripts", "interview notes", "HR documents"],
    expectedOutputs: ["People insight report", "themes", "risk flags"],
    artifactBehavior: "suggest_save",
    approvalBehavior: "none",
    retention: "keep",
  },
  {
    id: "financial-intelligence-engine",
    displayName: "Financial Intelligence Engine",
    sourceFiles: ["financial-intelligence-engine-v5.0.html"],
    expertGroup: "executive_finance",
    mappedAgents: ["executive"],
    summary: "Board-grade financial analysis across statements, models, and uploaded finance documents.",
    expectedInputs: ["Financial statements", "models", "reports", "screenshots"],
    expectedOutputs: ["Financial review", "risk flags", "board questions"],
    artifactBehavior: "artifact_friendly",
    approvalBehavior: "none",
    retention: "keep",
  },
  {
    id: "golden-opportunities",
    displayName: "Golden Opportunities",
    sourceFiles: ["golden-opportunity-scanner.html", "golden-opportunities-v39/index.html"],
    expertGroup: "opportunity_analysis",
    mappedAgents: ["sales", "executive"],
    summary: "Multi-lens opportunity discovery, ranking, and recommendation engine.",
    expectedInputs: ["Company context", "goals", "constraints", "documents", "email or CRM context"],
    expectedOutputs: ["Ranked opportunities", "scorecards", "recommended plays"],
    artifactBehavior: "suggest_save",
    approvalBehavior: "hubspot_crm_write",
    retention: "merge",
    mergedIntoExpertTypes: ["opportunity_scorecard"],
  },
  {
    id: "hr-performance-review",
    displayName: "HR Performance Review",
    sourceFiles: ["hr-performance-review-v17.html"],
    expertGroup: "people_talent",
    mappedAgents: ["recruiting", "operations"],
    summary: "Performance review and PIP generation.",
    expectedInputs: ["Employee or team context", "evidence", "performance goals"],
    expectedOutputs: ["Review draft", "PIP draft", "coaching summary"],
    artifactBehavior: "artifact_friendly",
    approvalBehavior: "none",
    retention: "keep",
  },
  {
    id: "ima",
    displayName: "Intelligent Meeting Analyser",
    sourceFiles: ["ima-v3.55.html", "meeting-intelligence-v2.4.html"],
    expertGroup: "revenue_intelligence",
    mappedAgents: ["sales", "executive", "customer"],
    summary: "Pre-call and post-meeting intelligence covering dynamics, actions, coaching, and follow-up.",
    expectedInputs: ["Transcript", "meeting notes", "company/person context", "objectives"],
    expectedOutputs: ["Pre-call brief", "meeting debrief", "coaching guidance"],
    artifactBehavior: "suggest_save",
    approvalBehavior: "downstream_external_only",
    retention: "merge",
    mergedIntoExpertTypes: ["pre_call_brief"],
  },
  {
    id: "jobpulse-ai",
    displayName: "JobPulse AI",
    sourceFiles: ["jobpulse-ai-v1.4.html"],
    expertGroup: "people_talent",
    mappedAgents: ["recruiting"],
    summary: "Job market and role benchmarking intelligence.",
    expectedInputs: ["Role", "region", "hiring brief"],
    expectedOutputs: ["Talent market brief", "salary benchmark", "job ad rewrite"],
    artifactBehavior: "suggest_save",
    approvalBehavior: "none",
    retention: "keep",
  },
  {
    id: "legal-radar",
    displayName: "LegalRadar",
    sourceFiles: ["legal-radar-v1.3.html"],
    expertGroup: "legal_policy_ip",
    mappedAgents: ["operations", "research"],
    summary: "Scenario-based legal risk intelligence.",
    expectedInputs: ["Legal scenario", "jurisdiction", "uploaded text or files"],
    expectedOutputs: ["Risk assessment", "advice banner", "questions and references"],
    artifactBehavior: "suggest_save",
    approvalBehavior: "none",
    retention: "keep",
  },
  {
    id: "ma-command-center",
    displayName: "M&A Command Center",
    sourceFiles: ["ma-command-center-v2.html"],
    expertGroup: "opportunity_analysis",
    mappedAgents: ["executive"],
    summary: "M&A intelligence for buyers, valuation, outreach, and pipeline strategy.",
    expectedInputs: ["Company context", "buyer criteria", "documents", "deal goals"],
    expectedOutputs: ["M&A brief", "buyer universe", "valuation strategy"],
    artifactBehavior: "artifact_friendly",
    approvalBehavior: "downstream_external_only",
    retention: "keep",
  },
  {
    id: "marketing-hub",
    displayName: "Marketing Hub",
    sourceFiles: ["marketing-hub-v3.11.html", "PR_Intelligence_Engine_V16.html"],
    expertGroup: "outreach_messaging",
    mappedAgents: ["operations", "sales", "customer"],
    summary: "Campaign, sequence, and response drafting across email, scripts, and PR-style communications.",
    expectedInputs: ["Campaign brief", "audience", "offer", "channel", "narrative context"],
    expectedOutputs: ["Draft messages", "sequences", "response strategies"],
    artifactBehavior: "save_on_request",
    approvalBehavior: "gmail_send",
    retention: "merge",
    mergedIntoExpertTypes: ["outreach_draft"],
  },
  {
    id: "patent-engine",
    displayName: "Patent Engine",
    sourceFiles: ["patent-engine-v2.2.html"],
    expertGroup: "legal_policy_ip",
    mappedAgents: ["research"],
    summary: "Patent drafting, novelty analysis, and prior-art warbook support.",
    expectedInputs: ["Idea description", "prior art", "uploaded docs"],
    expectedOutputs: ["Patent analysis", "claim strategy", "warbook"],
    artifactBehavior: "artifact_friendly",
    approvalBehavior: "none",
    retention: "keep",
  },
  {
    id: "pocket-brief",
    displayName: "Pocket Brief",
    sourceFiles: ["pocket-brief-v1.7.html"],
    expertGroup: "executive_finance",
    mappedAgents: ["executive", "operations"],
    summary: "Condenses complex information into decision-ready executive briefs.",
    expectedInputs: ["Document", "topic", "long text"],
    expectedOutputs: ["Executive summary", "decision brief"],
    artifactBehavior: "suggest_save",
    approvalBehavior: "none",
    retention: "keep",
  },
  {
    id: "policy-sop-centre",
    displayName: "Policy & SOP Centre",
    sourceFiles: ["policy-sop-centre-v2.28.html"],
    expertGroup: "legal_policy_ip",
    mappedAgents: ["operations"],
    summary: "Policy, SOP, and compliance document generation.",
    expectedInputs: ["Process area", "company context", "requirements"],
    expectedOutputs: ["Policy draft", "SOP draft", "compliance checklist"],
    artifactBehavior: "artifact_friendly",
    approvalBehavior: "none",
    retention: "keep",
  },
  {
    id: "pre-call-intelligence",
    displayName: "Pre-Call Intelligence",
    sourceFiles: ["pre-call-intelligence-v2.4.html"],
    expertGroup: "revenue_intelligence",
    mappedAgents: ["sales"],
    summary: "Call preparation engine for prospects and accounts.",
    expectedInputs: ["Company URL", "LinkedIn or contact details", "call objective"],
    expectedOutputs: ["Pre-call brief", "questions", "objections", "opening lines"],
    artifactBehavior: "suggest_save",
    approvalBehavior: "none",
    retention: "keep",
  },
  {
    id: "report-intelligence",
    displayName: "Report Intelligence",
    sourceFiles: ["report-intelligence-full.html", "score-my-report.html", "signalboard-oracle-improvements.html", "signalboard-report-analysis.html"],
    expertGroup: "executive_finance",
    mappedAgents: ["executive", "research"],
    summary: "Report scoring, critique, benchmarking, and improvement analysis.",
    expectedInputs: ["Report or document", "target audience or benchmark lens"],
    expectedOutputs: ["Report scorecard", "improvement guidance", "benchmark notes"],
    artifactBehavior: "suggest_save",
    approvalBehavior: "none",
    retention: "merge",
    mergedIntoExpertTypes: ["competitor_battlecard", "signal_radar"],
  },
  {
    id: "signal-intelligence",
    displayName: "Signal Intelligence",
    sourceFiles: ["source-scout-v7.html", "signal-scout-v2.2.html", "Signal_Scout_v2.2.html", "signal-deep-intel-v1.1.html"],
    expertGroup: "market_research",
    mappedAgents: ["research", "executive", "sales"],
    summary: "Market and company signal detection, validation, and deeper follow-on investigation.",
    expectedInputs: ["Company or topic", "market frame", "signal question"],
    expectedOutputs: ["Signal radar", "deep intel brief", "recommended moves"],
    artifactBehavior: "suggest_save",
    approvalBehavior: "none",
    retention: "merge",
    mergedIntoExpertTypes: ["signal_radar"],
  },
];

