import { legacyArchiveInventory } from "./archiveInventory.js";
import { competitorBattlecardSchema } from "./schemas/competitorBattlecard.js";
import { contactBriefSchema } from "./schemas/contactBrief.js";
import { documentAnalysisSchema } from "./schemas/documentAnalysis.js";
import { opportunityScorecardSchema } from "./schemas/opportunityScorecard.js";
import { outreachDraftSchema } from "./schemas/outreachDraft.js";
import { preCallBriefSchema } from "./schemas/preCallBrief.js";
import { signalRadarSchema } from "./schemas/signalRadar.js";
import { accountSnapshotSchema } from "./schemas/accountSnapshot.js";
import { salesIntelligenceSchema } from "./schemas/salesIntelligence.js";
import { pipelineHealthSchema } from "./schemas/pipelineHealth.js";
import { dealRiskSchema } from "./schemas/dealRisk.js";
import { meetingSummarySchema } from "./schemas/meetingSummary.js";
import type { ExpertCapability, ExpertCapabilitySourcePromptModule } from "./types.js";

const sourceModule = (legacyId: string): ExpertCapabilitySourcePromptModule => {
  const entry = legacyArchiveInventory.find((candidate) => candidate.id === legacyId);
  if (!entry) {
    throw new Error(`Unknown legacy prompt module: ${legacyId}`);
  }

  return {
    legacyId: entry.id,
    sourceFiles: entry.sourceFiles,
    retainedAs: entry.retention,
  };
};

const common = {
  fallbackRendererKey: "generic-structured-result" as const,
  schemaVersion: "2026-05-legacy-capability-v1",
  maxPromptTokens: 3000,
  promptVersion: "legacy-capability-v1",
};

export const expertCapabilities: ExpertCapability[] = [
  {
    ...common,
    id: "contact_brief",
    expertType: "contact_brief",
    displayName: "Contact Brief",
    group: "revenue_intelligence",
    agentOwner: "sales",
    secondaryAgents: ["customer"],
    description: "Turns grounded prospect, contact, or account context into a concise buyer intelligence brief.",
    useCases: ["lead briefing", "contact research", "account context", "buyer pain and next steps"],
    aliases: ["contact intelligence", "lead brief", "buyer brief", "account brief", "prospect analysis"],
    sourcePromptModules: [sourceModule("contact-engine"), sourceModule("connection-intelligence")],
    lifecycleStatus: "active",
    requiredContext: ["hubspot_record"],
    optionalContext: ["gmail_thread", "company_or_person_details", "session_context"],
    groundingPolicy: "requires_resolved_record",
    inputSchema: { type: "object", required: ["request", "resolvedRecord"] },
    outputSchema: contactBriefSchema,
    rendererKey: "contact-brief-card",
    sopText:
      "Use CRM-backed contact and account context to identify buyer context, signals, pain points, recommended angle, risks, and next actions. \n\nCRITICAL RULES:\n1. NEVER invent CRM facts. Only use provided context.\n2. If required context is missing or too weak to produce a quality brief, return status: 'missing_context'. Do not guess.\n3. Keep the output strictly structured for rendering.",
    positiveExamples: ["brief this lead", "analyze this contact", "what should I know about this account"],
    negativeExamples: ["brief me on today's priorities", "analyze this idea", "summarize our product direction"],
    allowedRuntimeTools: ["hubspot.searchRecords", "hubspot.getRecordDetail"],
    approvalPolicy: "none",
    artifactPolicy: "suggest_save",
    workflowPolicy: "can_suggest_workflow",
    minimumConfidence: 0.72,
  },
  {
    ...common,
    id: "pre_call_brief",
    expertType: "pre_call_brief",
    displayName: "Pre-Call Brief",
    group: "revenue_intelligence",
    agentOwner: "sales",
    secondaryAgents: ["customer"],
    description: "Prepares call strategy, likely objections, opening lines, and success criteria from meeting or CRM/email context.",
    useCases: ["call prep", "meeting prep", "objection planning", "sales coaching before a meeting"],
    aliases: ["meeting intelligence", "pre-call intelligence", "call prep", "prospect call coach"],
    sourcePromptModules: [sourceModule("pre-call-intelligence"), sourceModule("ima"), sourceModule("connection-intelligence")],
    lifecycleStatus: "active",
    requiredContext: ["hubspot_record"],
    optionalContext: ["gmail_thread", "company_or_person_details", "session_context"],
    groundingPolicy: "requires_resolved_record",
    inputSchema: { type: "object", required: ["request", "meetingOrRecordContext"] },
    outputSchema: preCallBriefSchema,
    rendererKey: "pre-call-brief-card",
    sopText:
      "Use selected CRM, email, or meeting context to prepare the user for a call. Focus on objective, account context, objections, questions, opening lines, and success criteria.",
    positiveExamples: ["prep me for this call", "coach me for this sales call", "how should I open this meeting"],
    negativeExamples: ["schedule a call", "call this person now", "write meeting notes without transcript"],
    allowedRuntimeTools: ["hubspot.getRecordDetail", "gmail.getThread"],
    approvalPolicy: "none",
    artifactPolicy: "suggest_save",
    workflowPolicy: "none",
    minimumConfidence: 0.72,
  },
  {
    ...common,
    id: "opportunity_scorecard",
    expertType: "opportunity_scorecard",
    displayName: "Opportunity Scorecard",
    group: "opportunity_analysis",
    agentOwner: "sales",
    secondaryAgents: ["executive"],
    description: "Scores a deal or opportunity and recommends the next commercial play from grounded CRM/account context.",
    useCases: ["deal analysis", "pipeline review", "opportunity scoring", "next-step recommendation"],
    aliases: ["deal command centre", "golden opportunity", "deal scorecard", "opportunity analysis"],
    sourcePromptModules: [sourceModule("deal-command-centre"), sourceModule("golden-opportunities")],
    lifecycleStatus: "active",
    requiredContext: ["hubspot_record"],
    optionalContext: ["gmail_thread", "company_or_person_details", "session_context"],
    groundingPolicy: "requires_resolved_record",
    inputSchema: { type: "object", required: ["request", "dealOrAccountContext"] },
    outputSchema: opportunityScorecardSchema,
    rendererKey: "opportunity-scorecard",
    sopText:
      "Assess opportunity quality, why-now signals, account risks, recommended play, next steps, and CRM action hints using real deal/account context. \n\nCRITICAL RULES:\n1. NEVER invent CRM facts. Only score what is provided.\n2. If required context is missing or too weak, return status: 'missing_context'. Do not guess.\n3. Keep the output strictly structured for rendering.",
    positiveExamples: ["analyze this deal", "score this opportunity", "what should we do next on this deal"],
    negativeExamples: ["what is an opportunity", "create a generic sales strategy", "brainstorm startup ideas"],
    allowedRuntimeTools: ["hubspot.getRecordDetail", "hubspot.searchRecords"],
    approvalPolicy: "approval_required_for_crm_write",
    artifactPolicy: "suggest_save",
    workflowPolicy: "can_suggest_workflow",
    minimumConfidence: 0.74,
  },
  {
    ...common,
    id: "outreach_draft",
    expertType: "outreach_draft",
    displayName: "Outreach Draft",
    group: "outreach_messaging",
    agentOwner: "sales",
    secondaryAgents: ["operations", "customer", "executive"],
    description: "Creates grounded emails, replies, follow-ups, and campaign-style messages with rationale and variants.",
    useCases: ["draft email", "reply to thread", "follow-up", "campaign message", "rewrite"],
    aliases: ["creative studio", "marketing hub", "article writer", "iterative rewrite", "PR response"],
    sourcePromptModules: [sourceModule("creative-studio"), sourceModule("marketing-hub")],
    lifecycleStatus: "active",
    requiredContext: ["company_or_person_details"],
    optionalContext: ["gmail_thread", "hubspot_record", "session_context"],
    groundingPolicy: "can_use_user_supplied_context",
    inputSchema: { type: "object", required: ["request", "audienceOrThreadContext"] },
    outputSchema: outreachDraftSchema,
    rendererKey: "outreach-draft-card",
    sopText:
      "Draft concise, useful messaging from the user's brief and available context. Include audience, subject/body when relevant, rationale, variants, and confidence. \n\nCRITICAL RULES:\n1. NEVER invent facts about the user or target.\n2. If required target context is missing, return status: 'missing_context'. Do not guess.\n3. Keep the output strictly structured for rendering.\n4. You are drafting a PROPOSAL. Do not assume it is being sent immediately.",
    positiveExamples: ["draft a follow-up", "write a reply", "create an outreach email", "rewrite this message"],
    negativeExamples: ["send this email now", "update HubSpot", "summarize a contract"],
    allowedRuntimeTools: ["gmail.getThread", "hubspot.getRecordDetail"],
    approvalPolicy: "approval_required_for_email_send",
    artifactPolicy: "save_on_explicit_request",
    workflowPolicy: "none",
    minimumConfidence: 0.7,
  },
  {
    ...common,
    id: "competitor_battlecard",
    expertType: "competitor_battlecard",
    displayName: "Competitor Battlecard",
    group: "market_research",
    agentOwner: "research",
    secondaryAgents: ["sales", "executive"],
    description: "Produces a competitor comparison and practical attack angles from research or supplied market context.",
    useCases: ["competitor comparison", "battlecard", "positioning", "competitive sales enablement"],
    aliases: ["competitor watch", "competitive intelligence", "battlecard", "positioning gap"],
    sourcePromptModules: [sourceModule("competitor-watch")],
    lifecycleStatus: "active",
    requiredContext: ["web_research_context"],
    optionalContext: ["company_or_person_details", "session_context"],
    groundingPolicy: "requires_retrieved_sources",
    inputSchema: { type: "object", required: ["request", "competitorOrMarketContext"] },
    outputSchema: competitorBattlecardSchema,
    rendererKey: "competitor-battlecard",
    sopText:
      "Compare competitor strengths, weaknesses, positioning gaps, attack angles, and watch items. \n\nCRITICAL RULES:\n1. Preserve uncertainty and cite visible sources when available.\n2. NEVER invent web or source facts.\n3. If web research context is missing or too weak, return status: 'missing_context'. Do not hallucinate competitor features.\n4. Keep the output strictly structured for rendering.",
    positiveExamples: ["compare us to this competitor", "build a battlecard", "what are their weaknesses"],
    negativeExamples: ["compare two internal options", "what is my competitor today", "make this shorter"],
    allowedRuntimeTools: ["webResearch.run"],
    approvalPolicy: "none",
    artifactPolicy: "suggest_save",
    workflowPolicy: "can_suggest_workflow",
    minimumConfidence: 0.74,
  },
  {
    ...common,
    id: "signal_radar",
    expertType: "signal_radar",
    displayName: "Signal Radar",
    group: "market_research",
    agentOwner: "research",
    secondaryAgents: ["sales", "executive"],
    description: "Finds and ranks business signals, urgency, implications, and suggested moves.",
    useCases: ["market signals", "company changes", "why now", "research radar", "monitoring"],
    aliases: ["signal scout", "signal deep intel", "source scout", "market radar"],
    sourcePromptModules: [sourceModule("signal-intelligence")],
    lifecycleStatus: "active",
    requiredContext: ["web_research_context"],
    optionalContext: ["company_or_person_details", "session_context"],
    groundingPolicy: "requires_retrieved_sources",
    inputSchema: { type: "object", required: ["request", "topicOrCompanyContext"] },
    outputSchema: signalRadarSchema,
    rendererKey: "signal-radar-card",
    sopText:
      "Identify important business signals, explain why each matters, estimate urgency, and recommend practical moves. \n\nCRITICAL RULES:\n1. NEVER invent signals or web facts.\n2. If research context is missing, return status: 'missing_context'. Do not guess.\n3. Keep the output strictly structured for rendering.",
    positiveExamples: ["what signals matter here", "what changed in this market", "scan for business signals"],
    negativeExamples: ["signal me when done", "what is a signal", "turn on monitoring without a target"],
    allowedRuntimeTools: ["webResearch.run"],
    approvalPolicy: "none",
    artifactPolicy: "suggest_save",
    workflowPolicy: "can_suggest_workflow",
    minimumConfidence: 0.72,
  },
  {
    ...common,
    id: "document_analysis",
    expertType: "document_analysis",
    displayName: "Document Analysis",
    group: "market_research",
    agentOwner: "research",
    secondaryAgents: ["executive", "sales", "operations", "customer", "recruiting"],
    description: "Analyzes an uploaded or retrieved workspace document with a generic structured fallback renderer.",
    useCases: ["document summary", "report analysis", "file explanation"],
    aliases: ["document analysis", "file analysis", "report summary"],
    sourcePromptModules: [],
    lifecycleStatus: "active",
    requiredContext: [],
    optionalContext: ["session_context"],
    groundingPolicy: "requires_uploaded_document",
    inputSchema: { type: "object", required: ["request", "documentContext"] },
    outputSchema: documentAnalysisSchema,
    rendererKey: "expert-result-renderer",
    sopText: "Analyze only the selected or retrieved document context. If no document is present, return a missing-context result.",
    positiveExamples: ["summarize this document", "analyze this report", "what does this file say"],
    negativeExamples: ["analyze this contact", "analyze this deal", "list HubSpot contacts"],
    allowedRuntimeTools: ["document.retrieve"],
    approvalPolicy: "none",
    artifactPolicy: "save_on_explicit_request",
    workflowPolicy: "none",
    minimumConfidence: 0.78,
  },
  {
    ...common,
    id: "account_snapshot",
    expertType: "account_snapshot",
    displayName: "Account Snapshot",
    group: "revenue_intelligence",
    agentOwner: "sales",
    secondaryAgents: ["executive"],
    description: "Provides a high-level summary of account health, recent activity, and CRM status.",
    useCases: ["account health", "latest activity", "crm status"],
    aliases: ["account health", "account snapshot"],
    sourcePromptModules: [],
    lifecycleStatus: "active",
    requiredContext: ["hubspot_record"],
    optionalContext: ["session_context"],
    groundingPolicy: "requires_resolved_record",
    inputSchema: { type: "object", required: ["request", "recordContext"] },
    outputSchema: accountSnapshotSchema,
    rendererKey: "account-snapshot-card",
    sopText: "Provide an account snapshot from CRM data.",
    positiveExamples: ["give me an account snapshot", "account health", "latest on this account"],
    negativeExamples: ["draft an email", "compare competitors"],
    allowedRuntimeTools: ["hubspot.getRecordDetail", "hubspot.searchRecords"],
    approvalPolicy: "none",
    artifactPolicy: "save_on_explicit_request",
    workflowPolicy: "none",
    minimumConfidence: 0.72,
  },
  {
    ...common,
    id: "sales_intelligence",
    expertType: "sales_intelligence",
    displayName: "Sales Intelligence",
    group: "revenue_intelligence",
    agentOwner: "sales",
    secondaryAgents: ["research"],
    description: "Pulls sales intel, firmographics, and tech stack information for a company.",
    useCases: ["sales intel", "tech stack", "firmographics"],
    aliases: ["sales intel", "company intel"],
    sourcePromptModules: [],
    lifecycleStatus: "active",
    requiredContext: ["company_or_person_details"],
    optionalContext: ["session_context"],
    groundingPolicy: "can_use_user_supplied_context",
    inputSchema: { type: "object", required: ["request", "companyContext"] },
    outputSchema: salesIntelligenceSchema,
    rendererKey: "sales-intelligence-card",
    sopText:
      "Extract sales intelligence and tech stack from available company context. \n\nCRITICAL RULES:\n1. NEVER invent facts. Only use provided context.\n2. If required context is missing, return status: 'missing_context'. Do not guess.\n3. Keep the output strictly structured for rendering.",
    positiveExamples: ["tell me about this company", "sales intel", "what is their tech stack"],
    negativeExamples: ["draft an email", "score a deal"],
    allowedRuntimeTools: ["hubspot.getRecordDetail", "hubspot.searchRecords"],
    approvalPolicy: "none",
    artifactPolicy: "suggest_save",
    workflowPolicy: "can_suggest_workflow",
    minimumConfidence: 0.72,
  },
  {
    ...common,
    id: "pipeline_health",
    expertType: "pipeline_health",
    displayName: "Pipeline Health",
    group: "revenue_intelligence",
    agentOwner: "sales",
    secondaryAgents: ["executive"],
    description: "Evaluates overall pipeline health, deal flow, and forecast.",
    useCases: ["pipeline", "funnel", "deal flow", "forecast"],
    aliases: ["pipeline health", "pipeline overview"],
    sourcePromptModules: [],
    lifecycleStatus: "active",
    requiredContext: [],
    optionalContext: ["session_context"],
    groundingPolicy: "can_run_without_workspace_context",
    inputSchema: { type: "object", required: ["request"] },
    outputSchema: pipelineHealthSchema,
    rendererKey: "pipeline-health-card",
    sopText: "Analyze pipeline health from aggregate CRM data.",
    positiveExamples: ["how is my pipeline", "pipeline health", "show me my deals"],
    negativeExamples: ["draft an email", "analyze this specific deal"],
    allowedRuntimeTools: ["hubspot.searchRecords"],
    approvalPolicy: "none",
    artifactPolicy: "suggest_save",
    workflowPolicy: "can_suggest_workflow",
    minimumConfidence: 0.72,
  },
  {
    ...common,
    id: "deal_risk",
    expertType: "deal_risk",
    displayName: "Deal Risk",
    group: "opportunity_analysis",
    agentOwner: "sales",
    secondaryAgents: ["executive"],
    description: "Analyzes specific risks, red flags, and blockers for a selected deal.",
    useCases: ["risk", "at risk", "deal risk", "red flags"],
    aliases: ["deal risk analysis"],
    sourcePromptModules: [],
    lifecycleStatus: "active",
    requiredContext: ["hubspot_record"],
    optionalContext: ["session_context"],
    groundingPolicy: "requires_resolved_record",
    inputSchema: { type: "object", required: ["request", "dealContext"] },
    outputSchema: dealRiskSchema,
    rendererKey: "deal-risk-card",
    sopText: "Evaluate a deal for risks and red flags using CRM context.",
    positiveExamples: ["is this deal at risk", "what are the risks here", "deal risk analysis"],
    negativeExamples: ["draft an email", "score my report"],
    allowedRuntimeTools: ["hubspot.getRecordDetail", "hubspot.searchRecords"],
    approvalPolicy: "approval_required_for_crm_write",
    artifactPolicy: "suggest_save",
    workflowPolicy: "can_suggest_workflow",
    minimumConfidence: 0.72,
  },
  {
    ...common,
    id: "meeting_summary",
    expertType: "meeting_summary",
    displayName: "Meeting Summary",
    group: "revenue_intelligence",
    agentOwner: "sales",
    secondaryAgents: ["executive", "operations", "customer"],
    description: "Summarizes notes, action items, and decisions from a meeting or email thread.",
    useCases: ["meeting summary", "notes", "action items", "decisions", "follow-ups"],
    aliases: ["meeting notes", "call summary"],
    sourcePromptModules: [],
    lifecycleStatus: "active",
    requiredContext: ["gmail_thread"],
    optionalContext: ["hubspot_record", "session_context"],
    groundingPolicy: "requires_resolved_record",
    inputSchema: { type: "object", required: ["request", "meetingContext"] },
    outputSchema: meetingSummarySchema,
    rendererKey: "meeting-summary-card",
    sopText: "Summarize meeting notes and extract action items.",
    positiveExamples: ["summarize my last meeting", "meeting notes", "action items from the call"],
    negativeExamples: ["draft an email", "analyze a deal"],
    allowedRuntimeTools: ["gmail.getThread", "hubspot.getRecordDetail"],
    approvalPolicy: "none",
    artifactPolicy: "save_on_explicit_request",
    workflowPolicy: "can_suggest_workflow",
    minimumConfidence: 0.72,
  },
  {
    ...common,
    id: "meeting_debrief",
    displayName: "Meeting Debrief",
    group: "revenue_intelligence",
    agentOwner: "sales",
    secondaryAgents: ["customer", "executive"],
    description: "Future post-meeting debrief and sales coach capability from meeting transcripts and notes.",
    useCases: ["sales coach", "meeting debrief", "call coaching", "follow-up planning"],
    aliases: ["sales coach", "meeting analysis", "call debrief"],
    sourcePromptModules: [sourceModule("ima")],
    lifecycleStatus: "candidate",
    requiredContext: ["session_context"],
    optionalContext: ["hubspot_record", "gmail_thread"],
    groundingPolicy: "requires_retrieved_sources",
    inputSchema: { type: "object", required: ["request", "meetingNotesOrTranscript"] },
    outputSchema: { futureSchema: "meeting_debrief" },
    rendererKey: "meeting-debrief-card",
    sopText: "Use transcript or meeting notes to identify what happened, hidden dynamics, coaching advice, and next follow-up steps.",
    positiveExamples: ["coach me on this sales call", "debrief this meeting", "what did I miss in this call"],
    negativeExamples: ["prep me before the meeting", "schedule a meeting"],
    allowedRuntimeTools: ["hubspot.getRecordDetail", "gmail.getThread"],
    approvalPolicy: "approval_required_for_external_write",
    artifactPolicy: "suggest_save",
    workflowPolicy: "can_suggest_workflow",
    minimumConfidence: 0.76,
  },
  {
    ...common,
    id: "report_scorecard",
    displayName: "Report Scorecard",
    group: "executive_finance",
    agentOwner: "executive",
    secondaryAgents: ["research"],
    description: "Future report/deck scoring, critique, and improvement capability.",
    useCases: ["score my report", "review this deck", "improve this board memo"],
    aliases: ["report intelligence", "score my report", "signalboard"],
    sourcePromptModules: [sourceModule("report-intelligence")],
    lifecycleStatus: "candidate",
    requiredContext: [],
    optionalContext: ["session_context"],
    groundingPolicy: "requires_uploaded_document",
    inputSchema: { type: "object", required: ["request", "documentContext"] },
    outputSchema: { futureSchema: "report_scorecard" },
    rendererKey: "report-scorecard",
    sopText: "Evaluate report clarity, evidence quality, executive usefulness, risks, and concrete improvements.",
    positiveExamples: ["score my report", "review this deck", "improve this memo"],
    negativeExamples: ["write a sales email", "analyze a HubSpot contact"],
    allowedRuntimeTools: ["document.retrieve"],
    approvalPolicy: "none",
    artifactPolicy: "suggest_save",
    workflowPolicy: "none",
    minimumConfidence: 0.76,
  },
  {
    ...common,
    id: "executive_brief",
    displayName: "Executive Brief",
    group: "executive_finance",
    agentOwner: "executive",
    secondaryAgents: ["operations"],
    description: "Future executive brief capability for board packs, finance packs, and decision summaries.",
    useCases: ["board pack analysis", "executive summary", "finance review", "decision brief"],
    aliases: ["boardpack intelligence", "financial intelligence", "pocket brief"],
    sourcePromptModules: [
      sourceModule("boardpack-intelligence"),
      sourceModule("financial-intelligence-engine"),
      sourceModule("pocket-brief"),
    ],
    lifecycleStatus: "candidate",
    requiredContext: [],
    optionalContext: ["session_context"],
    groundingPolicy: "requires_uploaded_document",
    inputSchema: { type: "object", required: ["request", "executiveContext"] },
    outputSchema: { futureSchema: "executive_brief" },
    rendererKey: "executive-brief-card",
    sopText: "Condense complex business, board, or finance material into decision-ready executive guidance.",
    positiveExamples: ["make an executive brief", "summarize this board pack", "review these financials"],
    negativeExamples: ["draft a cold email", "create a CRM task"],
    allowedRuntimeTools: ["document.retrieve"],
    approvalPolicy: "none",
    artifactPolicy: "artifact_friendly_report",
    workflowPolicy: "none",
    minimumConfidence: 0.76,
  },
  {
    ...common,
    id: "ma_brief",
    displayName: "M&A Brief",
    group: "opportunity_analysis",
    agentOwner: "executive",
    secondaryAgents: ["sales"],
    description: "Future M&A intelligence capability for buyer universe, valuation, and outreach strategy.",
    useCases: ["buyer universe", "M&A strategy", "valuation narrative", "acquirer list"],
    aliases: ["M&A command center", "buyer universe", "acquirer strategy"],
    sourcePromptModules: [sourceModule("ma-command-center")],
    lifecycleStatus: "candidate",
    requiredContext: [],
    optionalContext: ["session_context", "company_or_person_details"],
    groundingPolicy: "can_use_user_supplied_context",
    inputSchema: { type: "object", required: ["request", "companyContext"] },
    outputSchema: { futureSchema: "ma_brief" },
    rendererKey: "buyer-universe-card",
    sopText: "Analyze strategic buyer fit, M&A narrative, valuation considerations, and outreach strategy.",
    positiveExamples: ["build a buyer universe", "who could acquire us", "prepare an M&A brief"],
    negativeExamples: ["score this sales deal", "write a customer email"],
    allowedRuntimeTools: ["webResearch.run"],
    approvalPolicy: "approval_required_for_external_write",
    artifactPolicy: "artifact_friendly_report",
    workflowPolicy: "can_suggest_workflow",
    minimumConfidence: 0.78,
  },
  {
    ...common,
    id: "legal_risk_panel",
    displayName: "Legal Risk Panel",
    group: "legal_policy_ip",
    agentOwner: "operations",
    secondaryAgents: ["research"],
    description: "Future legal risk and contract analysis capability.",
    useCases: ["contract risk", "legal scenario analysis", "clause comparison"],
    aliases: ["contractshield", "legal radar", "legal risk"],
    sourcePromptModules: [sourceModule("contractshield"), sourceModule("legal-radar")],
    lifecycleStatus: "candidate",
    requiredContext: [],
    optionalContext: ["session_context"],
    groundingPolicy: "requires_uploaded_document",
    inputSchema: { type: "object", required: ["request", "legalContext"] },
    outputSchema: { futureSchema: "legal_risk_panel" },
    rendererKey: "legal-risk-panel",
    sopText: "Assess legal risk, issue severity, contract clauses, and practical questions without pretending to be legal counsel.",
    positiveExamples: ["analyze this contract", "what are the legal risks", "compare these clauses"],
    negativeExamples: ["delete this contact", "send this email"],
    allowedRuntimeTools: ["document.retrieve"],
    approvalPolicy: "none",
    artifactPolicy: "suggest_save",
    workflowPolicy: "none",
    minimumConfidence: 0.8,
  },
  {
    ...common,
    id: "compliance_assessment",
    displayName: "Compliance Assessment",
    group: "legal_policy_ip",
    agentOwner: "operations",
    secondaryAgents: ["research"],
    description: "Future policy, SOP, and AI compliance assessment capability.",
    useCases: ["EU AI Act assessment", "policy draft", "SOP generation", "compliance checklist"],
    aliases: ["EU AI Act assessor", "policy SOP centre", "compliance checklist"],
    sourcePromptModules: [sourceModule("eu-ai-act-assessor"), sourceModule("policy-sop-centre")],
    lifecycleStatus: "candidate",
    requiredContext: [],
    optionalContext: ["session_context"],
    groundingPolicy: "can_use_user_supplied_context",
    inputSchema: { type: "object", required: ["request", "systemOrProcessContext"] },
    outputSchema: { futureSchema: "compliance_assessment" },
    rendererKey: "compliance-assessment-card",
    sopText: "Classify risk, identify compliance gaps, and produce practical SOP/policy/checklist outputs from supplied process context.",
    positiveExamples: ["assess this AI system under EU AI Act", "create an SOP", "build a compliance checklist"],
    negativeExamples: ["brief this sales lead", "draft a casual email"],
    allowedRuntimeTools: ["webResearch.run", "document.retrieve"],
    approvalPolicy: "none",
    artifactPolicy: "artifact_friendly_report",
    workflowPolicy: "none",
    minimumConfidence: 0.78,
  },
  {
    ...common,
    id: "patent_analysis",
    displayName: "Patent Analysis",
    group: "legal_policy_ip",
    agentOwner: "research",
    description: "Future patent novelty, prior-art, claim strategy, and invention analysis capability.",
    useCases: ["patent idea analysis", "novelty check", "prior art warbook", "claim strategy"],
    aliases: ["patent engine", "patent analysis", "prior art"],
    sourcePromptModules: [sourceModule("patent-engine")],
    lifecycleStatus: "candidate",
    requiredContext: [],
    optionalContext: ["session_context"],
    groundingPolicy: "can_use_user_supplied_context",
    inputSchema: { type: "object", required: ["request", "inventionContext"] },
    outputSchema: { futureSchema: "patent_analysis" },
    rendererKey: "patent-analysis-card",
    sopText: "Analyze invention novelty, similar areas, risk flags, claim angles, and research gaps from supplied invention and prior-art context.",
    positiveExamples: ["analyze this patent idea", "check novelty", "build a prior art warbook"],
    negativeExamples: ["write a marketing email", "score this CRM deal"],
    allowedRuntimeTools: ["webResearch.run", "document.retrieve"],
    approvalPolicy: "none",
    artifactPolicy: "artifact_friendly_report",
    workflowPolicy: "none",
    minimumConfidence: 0.78,
  },
  {
    ...common,
    id: "people_insight",
    displayName: "People Insight",
    group: "people_talent",
    agentOwner: "recruiting",
    secondaryAgents: ["operations", "executive"],
    description: "Future people and talent intelligence capability for exit interviews, performance reviews, and hiring markets.",
    useCases: ["exit interview analysis", "performance review", "job market brief", "talent benchmark"],
    aliases: ["exit interview analyzer", "HR performance review", "JobPulse"],
    sourcePromptModules: [
      sourceModule("exit-interview-analyzer"),
      sourceModule("hr-performance-review"),
      sourceModule("jobpulse-ai"),
    ],
    lifecycleStatus: "candidate",
    requiredContext: [],
    optionalContext: ["session_context"],
    groundingPolicy: "requires_uploaded_document",
    inputSchema: { type: "object", required: ["request", "peopleContext"] },
    outputSchema: { futureSchema: "people_insight" },
    rendererKey: "people-insight-card",
    sopText: "Analyze people/talent evidence for themes, risks, coaching needs, or market recommendations.",
    positiveExamples: ["analyze these exit interviews", "draft a performance review", "benchmark this role"],
    negativeExamples: ["analyze a competitor", "prepare a sales call"],
    allowedRuntimeTools: ["document.retrieve", "webResearch.run"],
    approvalPolicy: "none",
    artifactPolicy: "suggest_save",
    workflowPolicy: "none",
    minimumConfidence: 0.78,
  },
];

export const activeExpertCapabilities = expertCapabilities.filter(
  (capability) => capability.lifecycleStatus === "active",
);

export function getExpertCapability(capabilityId: string) {
  return expertCapabilities.find((capability) => capability.id === capabilityId) ?? null;
}

export function getExpertCapabilitiesForAgent(agentId: string | null) {
  if (!agentId) {
    return activeExpertCapabilities;
  }

  return activeExpertCapabilities.filter(
    (capability) => capability.agentOwner === agentId || capability.secondaryAgents?.includes(agentId as never),
  );
}
